version: '3.4'

services:
  git-cache-data:
    build:
      context: .
      dockerfile: git-cache-data/Dockerfile
    volumes:
      - git-cache-data-volume:/var/gitcache

  git-cache:
    image: gitcache
    depends_on:
      - git-cache-data
    build:
      context: .
      dockerfile: git-cache/Dockerfile
    volumes:
      - git-cache-data-volume:/var/gitcache

volumes:
  git-cache-data-volume:
