name: .NET Build/Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x']
    steps:
      - uses : actions/checkout@v2
      - name: Setup .NET SDK ${{matrix.dotnet-version}}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{matrix.dotnet-version}}
      - name: Install dependencies
        run: dotnet restore git-cache.sln
      - name: Build
        run: dotnet build --configuration Release --no-restore git-cache.sln
      - name: Test
        run: dotnet test --no-restore --verbosity normal git-cache.sln